networks:
    pulse-net:
        driver: bridge

services:
    # buffer layer and idempotency cache
    redis:
        image: redis:8.0-alpine
        container_name: pulse-redis
        command: redis-server --appendonly yes # persist stream data to disk
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - pulse-net
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 8s
            timeout: 4s
            retries: 4
            start_period: 4s

    # analytical columnar database
    clickhouse:
        image: clickhouse/clickhouse-server:25.8-alpine
        environment:
            CLICKHOUSE_USER: pulse_ch
            CLICKHOUSE_PASSWORD: pulse_ch_super_secret_password
            CLICKHOUSE_DB: pulse
        container_name: pulse-clickhouse
        restart: unless-stopped
        ports:
            - "8123:8123" # HTTP interface
            - "9000:9000" # native client interface
        networks:
            - pulse-net
        volumes:
            - clickhouse_data:/var/lib/clickhouse
            - ./infra/clickhouse:/docker-entrypoint-initdb.d
        ulimits:
            nofile:
                soft: 262144
                hard: 262144
        healthcheck:
            test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
            interval: 8s
            timeout: 4s
            retries: 4
            start_period: 16s

    # relational database
    postgres:
        image: postgres:16-alpine
        container_name: pulse-postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: pulse_pg
            POSTGRES_PASSWORD: pulse_pg_super_secret_password
            POSTGRES_DB: pulse
        ports:
            - "5432:5432"
        networks:
            - pulse-net
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./infra/postgres:/docker-entrypoint-initdb.d
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U pulse_pg -d pulse"]
            interval: 8s
            timeout: 4s
            retries: 4
            start_period: 16s

    # pulse api server
    pulse-api:
        build:
            context: .
            dockerfile: Dockerfile.api
        container_name: pulse-api
        restart: unless-stopped
        environment:
            - PULSE_ENV=production
            - PULSE_REDIS_ADDR=redis:6379
            - PULSE_PG_HOST=postgres
            - PULSE_PG_USER=pulse_pg
            - PULSE_PG_PASSWORD=pulse_pg_super_secret_password
            - PULSE_PG_DBNAME=pulse
        ports:
            - "8000:8000"
        networks:
            - pulse-net
        depends_on:
            redis:
                condition: service_healthy
            postgres:
                condition: service_healthy

    # hashicorp vault
    vault:
        image: hashicorp/vault:2.0
        container_name: pulse-vault
        user: "root"
        restart: unless-stopped
        environment:
            - VAULT_ADDR=http://127.0.0.1:8200
        cap_add:
            - IPC_LOCK
        ports:
            - "8200:8200"
        networks:
            - pulse-net
        volumes:
            - ./infra/vault/config:/vault/config
            - vault_data:/vault/data
        entrypoint: vault server -config=/vault/config/vault.hcl
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "-q",
                    "--spider",
                    "http://127.0.0.1:8200/v1/sys/health?standbyok=true",
                ]
            interval: 8s
            timeout: 4s
            retries: 4
            start_period: 8s

    # pulse workers
    pulse-worker:
        build:
            context: .
            dockerfile: Dockerfile.worker
        restart: unless-stopped
        environment:
            - PULSE_ENV=production
            - PULSE_CONCURRENCY=2
            - PULSE_REDIS_ADDR=redis:6379
            - PULSE_CLICKHOUSE_ADDR=clickhouse:9000
            - PULSE_CLICKHOUSE_USER=pulse_ch
            - PULSE_CLICKHOUSE_PASSWORD=pulse_ch_super_secret_password
            - PULSE_CLICKHOUSE_DATABASE=pulse
        networks:
            - pulse-net
        deploy:
            replicas: 2
        depends_on:
            redis:
                condition: service_healthy
            clickhouse:
                condition: service_healthy

    prometheus:
        image: prom/prometheus:v3.0.0
        container_name: pulse-prometheus
        restart: unless-stopped
        ports:
            - "9090:9090"
        networks:
            - pulse-net
        volumes:
            - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_data:/prometheus

volumes:
    redis_data:
    clickhouse_data:
    postgres_data:
    prometheus_data:
    vault_data:
