# project identification
sonar.projectKey=Pulse
sonar.projectName=Pulse
sonar.projectVersion=1.0

# source settings
sonar.sources=.
sonar.exclusions=**/*_test.go,.go_dist/**

# test settings
sonar.tests=cmd,pkg
sonar.test.inclusions=**/*_test.go

# go specific settings
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=report.json
