# Project identification
sonar.projectKey=pulse
sonar.projectName=Pulse
sonar.projectVersion=1.0

# Source settings
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,docs/**,tmp/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**

# Go specific settings
sonar.go.coverage.reportPaths=coverage.out
sonar.go.tests.reportPaths=report.json

# Server settings (can also be passed via command line)
# sonar.host.url=http://localhost:9001
