---
# postgres secrets
apiVersion: v1
kind: Secret
metadata:
    name: pg-secrets
    namespace: pulse
    labels:
        app: secrets
type: Opaque
data:
    POSTGRES_PASSWORD: "<base-64-placeholder>"
---
# clickhouse secrets
apiVersion: v1
kind: Secret
metadata:
    name: ch-secrets
    namespace: pulse
    labels:
        app: secrets
type: Opaque
data:
    CLICKHOUSE_PASSWORD: "<base-64-placeholder>"
