services:
    jenkins:
        image: jenkins/jenkins:lts
        container_name: pulse-jenkins
        user: root
        restart: unless-stopped
        ports:
            - "12000:8080"
            - "50000:50000"
        networks:
            - pulse-net
        volumes:
            - jenkins_home:/var/jenkins_home
