global:
    scrape_interval: 15s

scrape_configs:
    - job_name: pulse_api
      static_configs:
          - targets: ["pulse-api:8000"]

    - job_name: pulse_worker
      dns_sd_configs:
          - names:
                - "pulse-worker"
            type: "A"
            port: 9091
